Repository trufflesuite/vscode-ext, pull requests merged in 2022-09, with the labels that each got.

#218 Always use the embedded Debug Adapter
  .vscodeignore
  package.json
  src/debugAdapter/configuration/debuggerConfiguration.ts
  src/debugAdapter/constants/debugAdapter.ts
  src/debugAdapter/debugNetwork.ts
  src/debugAdapter/types/webpackVariables.d.ts
  src/debugAdapter/web3ProviderResolver.js
  src/debugger.ts
  src/helpers/debugConfigurationReader.ts
  webpack.common.js
  webpack.prod.js
Labels: bug

#215 fix: change gfx
  images/TruffleLogo.png
Labels: enhancement

#227 Create an "auto-deploy on save" toggle in the Contract Explorer
  package.json
  src/Constants.ts
  src/Models/StatusBarItems/Contract.ts
  src/commands/ContractCommands.ts
  src/commands/TruffleCommands.ts
  src/extension.ts
  src/helpers/workspace.ts
  src/services/contract/ContractService.ts
  test/TruffleCommandsTests/WriteToBuffer.test.ts
Labels: doc-change-required
