Repository trufflesuite/vscode-ext, pull requests merged in 2022-11, with the labels that each got.

#231 Feat: Running truffle debug with appropriate flag (--vscode) triggers debugger to launch / run in VS Code
  src/Constants.ts
  src/commands/DebuggerCommands.ts
  src/extension.ts
  src/helpers/uriHandlerController.ts
Labels: enhancement

#254 Running truffle debug with appropriate flag (--vscode) - Enhancements & Fixes
  package.json
  src/commands/DebuggerCommands.ts
  src/debugAdapter/debugNetwork.ts
  src/debugAdapter/models/debuggerTypes.ts
  src/helpers/uriHandlerController.ts
  test/commands/DebuggerCommands.test.ts
Labels: bug, enhancement, refactor

#252 Fetch external sources when debugging a forked network
  package.json
  src/commands/DebuggerCommands.ts
  src/debugAdapter/debugNetwork.ts
  src/debugAdapter/runtimeInterface.ts
  src/debugAdapter/types/@truffle/debugger.d.ts
  src/functions/explorer.ts
  src/helpers/ConfigurationReader.ts
  test/commands/DebuggerCommands.test.ts
  yarn.lock
Labels: doc-change-required

#255 Include `disableFetchExternal` flag to avoid debugging with fetching external sources
  package.json
  src/commands/DebuggerCommands.ts
  src/debugAdapter/constants/contractJson.ts
  src/debugAdapter/constants/transaction.ts
  src/debugAdapter/constants/truffleConfig.ts
  src/debugAdapter/constants/variablesView.ts
  src/debugAdapter/contracts/contractJsonsProvider.ts
  src/debugAdapter/debugNetwork.ts
  src/debugAdapter/debugSession.ts
  src/debugAdapter/functions.ts
  src/debugAdapter/helpers.ts
  src/debugAdapter/models/debuggerTypes.ts
  src/debugAdapter/runtimeInterface.ts
  src/debugAdapter/transaction/transactionInputDataDecoder.ts
  src/debugAdapter/transaction/transactionProvider.ts
  src/debugAdapter/variablesHandler.ts
  src/helpers/uriHandlerController.ts
  test/commands/DebuggerCommands.test.ts
  test/debugAdapter/SolidityDebugSessionClient.ts
  test/debugAdapter/runtimeInterface.test.ts
  test/debugAdapter/variablesHandler.test.ts
Labels: enhancement, doc-change-required
